<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:urn="urn:sap-com:document:sap:soap:functions:mc-style">
    <soapenv:Header/>
    <soapenv:Body>
        <urn:ZmdmMaterialSavedata>
            <!--Optional:-->
            <Clientdata>
                <!--Zero or more repetitions:-->
                <item>
                    <#list map?keys as key>
                        android:id="@+id/${key}"
                    </#list>
                </item>
            </Clientdata>
            <!--Optional:-->
            <Clientdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <DelFlag>?</DelFlag>
                    <MatlGroup>?</MatlGroup>
                    <OldMatNo>?</OldMatNo>
                    <BaseUom>?</BaseUom>
                    <BaseUomIso>?</BaseUomIso>
                    <PoUnit>?</PoUnit>
                    <PoUnitIso>?</PoUnitIso>
                    <Document>?</Document>
                    <DocType>?</DocType>
                    <DocVers>?</DocVers>
                    <DocFormat>?</DocFormat>
                    <DocChgNo>?</DocChgNo>
                    <PageNo>?</PageNo>
                    <NoSheets>?</NoSheets>
                    <ProdMemo>?</ProdMemo>
                    <Pageformat>?</Pageformat>
                    <SizeDim>?</SizeDim>
                    <BasicMatl>?</BasicMatl>
                    <StdDescr>?</StdDescr>
                    <DsnOffice>?</DsnOffice>
                    <PurValkey>?</PurValkey>
                    <NetWeight>?</NetWeight>
                    <UnitOfWt>?</UnitOfWt>
                    <UnitOfWtIso>?</UnitOfWtIso>
                    <Container>?</Container>
                    <StorConds>?</StorConds>
                    <TempConds>?</TempConds>
                    <TransGrp>?</TransGrp>
                    <HazMatNo>?</HazMatNo>
                    <Division>?</Division>
                    <Competitor>?</Competitor>
                    <QtyGrGi>?</QtyGrGi>
                    <ProcRule>?</ProcRule>
                    <SupSource>?</SupSource>
                    <Season>?</Season>
                    <LabelType>?</LabelType>
                    <LabelForm>?</LabelForm>
                    <ProdHier>?</ProdHier>
                    <CadId>?</CadId>
                    <AllowedWt>?</AllowedWt>
                    <PackWtUn>?</PackWtUn>
                    <PackWtUnIso>?</PackWtUnIso>
                    <AllwdVol>?</AllwdVol>
                    <PackVoUn>?</PackVoUn>
                    <PackVoUnIso>?</PackVoUnIso>
                    <WtTolLt>?</WtTolLt>
                    <VolTolLt>?</VolTolLt>
                    <VarOrdUn>?</VarOrdUn>
                    <BatchMgmt>?</BatchMgmt>
                    <ShMatTyp>?</ShMatTyp>
                    <FillLevel>?</FillLevel>
                    <StackFact>?</StackFact>
                    <MatGrpSm>?</MatGrpSm>
                    <Authoritygroup>?</Authoritygroup>
                    <QmProcmnt>?</QmProcmnt>
                    <Catprofile>?</Catprofile>
                    <Minremlife>?</Minremlife>
                    <ShelfLife>?</ShelfLife>
                    <StorPct>?</StorPct>
                    <PurStatus>?</PurStatus>
                    <SalStatus>?</SalStatus>
                    <Pvalidfrom>?</Pvalidfrom>
                    <Svalidfrom>?</Svalidfrom>
                    <EnvtRlvt>?</EnvtRlvt>
                    <ProdAlloc>?</ProdAlloc>
                    <QualDik>?</QualDik>
                    <ManuMat>?</ManuMat>
                    <MfrNo>?</MfrNo>
                    <InvMatNo>?</InvMatNo>
                    <ManufProf>?</ManufProf>
                    <Hazmatprof>?</Hazmatprof>
                    <HighVisc>?</HighVisc>
                    <Looseorliq>?</Looseorliq>
                    <ClosedBox>?</ClosedBox>
                    <AppdBRec>?</AppdBRec>
                    <Matcmpllvl>?</Matcmpllvl>
                    <ParEff>?</ParEff>
                    <RoundUpRuleExpirationDate>?</RoundUpRuleExpirationDate>
                    <PeriodIndExpirationDate>?</PeriodIndExpirationDate>
                    <ProdCompositionOnPackaging>?</ProdCompositionOnPackaging>
                    <ItemCat>?</ItemCat>
                    <HazMatNoExternal>?</HazMatNoExternal>
                    <HazMatNoGuid>?</HazMatNoGuid>
                    <HazMatNoVersion>?</HazMatNoVersion>
                    <InvMatNoExternal>?</InvMatNoExternal>
                    <InvMatNoGuid>?</InvMatNoGuid>
                    <InvMatNoVersion>?</InvMatNoVersion>
                    <MaterialFixed>?</MaterialFixed>
                    <CmRelevanceFlag>?</CmRelevanceFlag>
                    <SledBbd>?</SledBbd>
                    <GtinVariant>?</GtinVariant>
                    <SerializationLevel>?</SerializationLevel>
                    <PlRefMat>?</PlRefMat>
                    <Extmatlgrp>?</Extmatlgrp>
                    <Uomusage>?</Uomusage>
                    <GdsRelevant>?</GdsRelevant>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <PlRefMatExternal>?</PlRefMatExternal>
                    <PlRefMatGuid>?</PlRefMatGuid>
                    <PlRefMatVersion>?</PlRefMatVersion>
                    <WeOriginAcceptance>?</WeOriginAcceptance>
                    <StdHuType>?</StdHuType>
                    <Pilferable>?</Pilferable>
                    <WhseStorageCondition>?</WhseStorageCondition>
                    <WhseMaterialGroup>?</WhseMaterialGroup>
                    <HandlingIndicator>?</HandlingIndicator>
                    <HazMatRelevant>?</HazMatRelevant>
                    <HuType>?</HuType>
                    <VariableTareWeight>?</VariableTareWeight>
                    <MaxAllowedCapacity>?</MaxAllowedCapacity>
                    <OvercapacityTolerance>?</OvercapacityTolerance>
                    <MaxAllowedLength>?</MaxAllowedLength>
                    <MaxAllowedWidth>?</MaxAllowedWidth>
                    <MaxAllowedHeigth>?</MaxAllowedHeigth>
                    <MaxDimensionUn>?</MaxDimensionUn>
                    <MaxDimensionUnIso>?</MaxDimensionUnIso>
                    <Countryori>?</Countryori>
                    <CountryoriIso>?</CountryoriIso>
                    <Matfrgtgrp>?</Matfrgtgrp>
                    <QuarantinePeriod>?</QuarantinePeriod>
                    <QuarantinePeriodUn>?</QuarantinePeriodUn>
                    <QuarantinePeriodUnIso>?</QuarantinePeriodUnIso>
                    <QualityInspGrp>?</QualityInspGrp>
                    <SerialNumberProfile>?</SerialNumberProfile>
                    <EwmCwToleranceGroup>?</EwmCwToleranceGroup>
                    <EwmCwInputControl>?</EwmCwInputControl>
                    <PckgingSmartform>?</PckgingSmartform>
                    <Pacod>?</Pacod>
                    <DgPckgingStatus>?</DgPckgingStatus>
                    <AdjustProfile>?</AdjustProfile>
                    <Ipmipproduct>?</Ipmipproduct>
                    <Medium>?</Medium>
                    <Nsnid>?</Nsnid>
                    <PhysicalCommodity>?</PhysicalCommodity>
                    <SegmentationStructure>?</SegmentationStructure>
                    <SegmentationStrategy>?</SegmentationStrategy>
                    <SegmentationRelevance>?</SegmentationRelevance>
                    <Anp>?</Anp>
                    <MaterialLong>?</MaterialLong>
                    <OldMatNoLong>?</OldMatNoLong>
                    <HazMatNoLong>?</HazMatNoLong>
                    <InvMatNoLong>?</InvMatNoLong>
                    <PlRefMatLong>?</PlRefMatLong>
                </item>
            </Clientdatax>
            <!--Optional:-->
            <Extensionin>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Structure>?</Structure>
                    <Valuepart1>?</Valuepart1>
                    <Valuepart2>?</Valuepart2>
                    <Valuepart3>?</Valuepart3>
                    <Valuepart4>?</Valuepart4>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Extensionin>
            <!--Optional:-->
            <Extensioninx>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Structure>?</Structure>
                    <Valuepart1>?</Valuepart1>
                    <Valuepart2>?</Valuepart2>
                    <Valuepart3>?</Valuepart3>
                    <Valuepart4>?</Valuepart4>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Extensioninx>
            <!--Optional:-->
            <Forecastparameters>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <ForeProf>?</ForeProf>
                    <ModelSi>?</ModelSi>
                    <ModelSp>?</ModelSp>
                    <ParamOpt>?</ParamOpt>
                    <OptimLev>?</OptimLev>
                    <Initialize>?</Initialize>
                    <ForeModel>?</ForeModel>
                    <AlphaFact>?</AlphaFact>
                    <BetaFact>?</BetaFact>
                    <GammaFact>?</GammaFact>
                    <DeltaFact>?</DeltaFact>
                    <Tracklimit>?</Tracklimit>
                    <ForeDate>?</ForeDate>
                    <HistVals>?</HistVals>
                    <InitPds>?</InitPds>
                    <SeasonPds>?</SeasonPds>
                    <ExpostPds>?</ExpostPds>
                    <ForePds>?</ForePds>
                    <FixedPds>?</FixedPds>
                    <WtgGroup>?</WtgGroup>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Forecastparameters>
            <!--Optional:-->
            <Forecastparametersx>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <ForeProf>?</ForeProf>
                    <ModelSi>?</ModelSi>
                    <ModelSp>?</ModelSp>
                    <ParamOpt>?</ParamOpt>
                    <OptimLev>?</OptimLev>
                    <Initialize>?</Initialize>
                    <ForeModel>?</ForeModel>
                    <AlphaFact>?</AlphaFact>
                    <BetaFact>?</BetaFact>
                    <GammaFact>?</GammaFact>
                    <DeltaFact>?</DeltaFact>
                    <Tracklimit>?</Tracklimit>
                    <ForeDate>?</ForeDate>
                    <HistVals>?</HistVals>
                    <InitPds>?</InitPds>
                    <SeasonPds>?</SeasonPds>
                    <ExpostPds>?</ExpostPds>
                    <ForePds>?</ForePds>
                    <FixedPds>?</FixedPds>
                    <WtgGroup>?</WtgGroup>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Forecastparametersx>
            <!--Optional:-->
            <Forecastvalues>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <FirstDay>?</FirstDay>
                    <ForeValue>?</ForeValue>
                    <CorrValue>?</CorrValue>
                    <SeasIndex>?</SeasIndex>
                    <CvalueFxd>?</CvalueFxd>
                    <ExpostVal>?</ExpostVal>
                    <ValRatio>?</ValRatio>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Forecastvalues>
            <!--Optional:-->
            <Headdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <IndSector>?</IndSector>
                    <MatlType>?</MatlType>
                    <BasicView>?</BasicView>
                    <SalesView>?</SalesView>
                    <PurchaseView>?</PurchaseView>
                    <MrpView>?</MrpView>
                    <ForecastView>?</ForecastView>
                    <WorkSchedView>?</WorkSchedView>
                    <PrtView>?</PrtView>
                    <StorageView>?</StorageView>
                    <WarehouseView>?</WarehouseView>
                    <QualityView>?</QualityView>
                    <AccountView>?</AccountView>
                    <CostView>?</CostView>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Headdata>
            <!--Optional:-->
            <Inspectionctrl>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Insptype>?</Insptype>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <IndInspWithTskList>?</IndInspWithTskList>
                    <IndSpecMatspec>?</IndSpecMatspec>
                    <IndSpecConfig>?</IndSpecConfig>
                    <IndSpecBatch>?</IndSpecBatch>
                    <IndAutoAssign>?</IndAutoAssign>
                    <IndInspByCharac>?</IndInspByCharac>
                    <IndPostToInspStock>?</IndPostToInspStock>
                    <IndAutomaticUd>?</IndAutomaticUd>
                    <SamplingProcedure>?</SamplingProcedure>
                    <DynModifRule>?</DynModifRule>
                    <InspPercentage>?</InspPercentage>
                    <Ind100PercentInspection>?</Ind100PercentInspection>
                    <IndSkipsAllowed>?</IndSkipsAllowed>
                    <IndManualSample>?</IndManualSample>
                    <IndManualSampleCalc>?</IndManualSampleCalc>
                    <IndSingleUnitsPossible>?</IndSingleUnitsPossible>
                    <AveInspDuration>?</AveInspDuration>
                    <ContrInspLotCreate>?</ContrInspLotCreate>
                    <QualScoreProcedure>?</QualScoreProcedure>
                    <AllowedScrapShare>?</AllowedScrapShare>
                    <IndSpecialQmOrder>?</IndSpecialQmOrder>
                    <QmOrderid>?</QmOrderid>
                    <IndInsptypeMatActive>?</IndInsptypeMatActive>
                    <PreferredInsptype>?</PreferredInsptype>
                    <InsptypeDelete>?</InsptypeDelete>
                    <CreationTime>?</CreationTime>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <IndHuInspection>?</IndHuInspection>
                    <MsFlag>?</MsFlag>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Inspectionctrl>
            <!--Optional:-->
            <Internationalartnos>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Unit>?</Unit>
                    <UnitIso>?</UnitIso>
                    <EanUpc>?</EanUpc>
                    <EanCat>?</EanCat>
                    <DelFlag>?</DelFlag>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Internationalartnos>
            <!--Optional:-->
            <Materialdescription>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Langu>?</Langu>
                    <LanguIso>?</LanguIso>
                    <MatlDesc>?</MatlDesc>
                    <DelFlag>?</DelFlag>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Materialdescription>
            <!--Optional:-->
            <Materiallongtext>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Applobject>?</Applobject>
                    <TextName>?</TextName>
                    <TextId>?</TextId>
                    <Langu>?</Langu>
                    <LanguIso>?</LanguIso>
                    <FormatCol>?</FormatCol>
                    <TextLine>?</TextLine>
                    <DelFlag>?</DelFlag>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                    <TextNameS4>?</TextNameS4>
                </item>
            </Materiallongtext>
            <!--Optional:-->
            <Planningdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <PlngMatl>?</PlngMatl>
                    <PlngPlant>?</PlngPlant>
                    <Convfactor>?</Convfactor>
                    <PlngMatlExternal>?</PlngMatlExternal>
                    <PlngMatlGuid>?</PlngMatlGuid>
                    <PlngMatlVersion>?</PlngMatlVersion>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                    <PlngMatlLong>?</PlngMatlLong>
                </item>
            </Planningdata>
            <!--Optional:-->
            <Planningdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <PlngMatl>?</PlngMatl>
                    <PlngPlant>?</PlngPlant>
                    <Convfactor>?</Convfactor>
                    <PlngMatlExternal>?</PlngMatlExternal>
                    <PlngMatlGuid>?</PlngMatlGuid>
                    <PlngMatlVersion>?</PlngMatlVersion>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                    <PlngMatlLong>?</PlngMatlLong>
                </item>
            </Planningdatax>
            <!--Optional:-->
            <Plantdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <DelFlag>?</DelFlag>
                    <AbcId>?</AbcId>
                    <CritPart>?</CritPart>
                    <PurGroup>?</PurGroup>
                    <IssueUnit>?</IssueUnit>
                    <IssueUnitIso>?</IssueUnitIso>
                    <Mrpprofile>?</Mrpprofile>
                    <MrpType>?</MrpType>
                    <MrpCtrler>?</MrpCtrler>
                    <PlndDelry>?</PlndDelry>
                    <GrPrTime>?</GrPrTime>
                    <PeriodInd>?</PeriodInd>
                    <AssyScrap>?</AssyScrap>
                    <Lotsizekey>?</Lotsizekey>
                    <ProcType>?</ProcType>
                    <Spproctype>?</Spproctype>
                    <ReorderPt>?</ReorderPt>
                    <SafetyStk>?</SafetyStk>
                    <Minlotsize>?</Minlotsize>
                    <Maxlotsize>?</Maxlotsize>
                    <FixedLot>?</FixedLot>
                    <RoundVal>?</RoundVal>
                    <MaxStock>?</MaxStock>
                    <OrdCosts>?</OrdCosts>
                    <DepReqId>?</DepReqId>
                    <StorCosts>?</StorCosts>
                    <AltBomId>?</AltBomId>
                    <Discontinu>?</Discontinu>
                    <EffODay>?</EffODay>
                    <FollowUp>?</FollowUp>
                    <GrpReqmts>?</GrpReqmts>
                    <MixedMrp>?</MixedMrp>
                    <SmKey>?</SmKey>
                    <Backflush>?</Backflush>
                    <ProductionScheduler>?</ProductionScheduler>
                    <ProcTime>?</ProcTime>
                    <Setuptime>?</Setuptime>
                    <Interop>?</Interop>
                    <BaseQty>?</BaseQty>
                    <Inhseprodt>?</Inhseprodt>
                    <Stgeperiod>?</Stgeperiod>
                    <StgePdUn>?</StgePdUn>
                    <StgePdUnIso>?</StgePdUnIso>
                    <OverTol>?</OverTol>
                    <Unlimited>?</Unlimited>
                    <UnderTol>?</UnderTol>
                    <Replentime>?</Replentime>
                    <ReplacePt>?</ReplacePt>
                    <IndPostToInspStock>?</IndPostToInspStock>
                    <CtrlKey>?</CtrlKey>
                    <DocReqd>?</DocReqd>
                    <Loadinggrp>?</Loadinggrp>
                    <BatchMgmt>?</BatchMgmt>
                    <Quotausage>?</Quotausage>
                    <ServLevel>?</ServLevel>
                    <SplitInd>?</SplitInd>
                    <Availcheck>?</Availcheck>
                    <FyVariant>?</FyVariant>
                    <CorrFact>?</CorrFact>
                    <SetupTime>?</SetupTime>
                    <BaseQtyPlan>?</BaseQtyPlan>
                    <ShipProcTime>?</ShipProcTime>
                    <SupSource>?</SupSource>
                    <AutoPOrd>?</AutoPOrd>
                    <Sourcelist>?</Sourcelist>
                    <CommCode>?</CommCode>
                    <Countryori>?</Countryori>
                    <CountryoriIso>?</CountryoriIso>
                    <Regionorig>?</Regionorig>
                    <CommCoUn>?</CommCoUn>
                    <CommCoUnIso>?</CommCoUnIso>
                    <Expimpgrp>?</Expimpgrp>
                    <ProfitCtr>?</ProfitCtr>
                    <PpcPlCal>?</PpcPlCal>
                    <RepManuf>?</RepManuf>
                    <PlTiFnce>?</PlTiFnce>
                    <Consummode>?</Consummode>
                    <BwdCons>?</BwdCons>
                    <FwdCons>?</FwdCons>
                    <AlternativeBom>?</AlternativeBom>
                    <BomUsage>?</BomUsage>
                    <Planlistgrp>?</Planlistgrp>
                    <Planlistcnt>?</Planlistcnt>
                    <LotSize>?</LotSize>
                    <Specprocty>?</Specprocty>
                    <ProdUnit>?</ProdUnit>
                    <ProdUnitIso>?</ProdUnitIso>
                    <IssStLoc>?</IssStLoc>
                    <MrpGroup>?</MrpGroup>
                    <CompScrap>?</CompScrap>
                    <CertType>?</CertType>
                    <CycleTime>?</CycleTime>
                    <Covprofile>?</Covprofile>
                    <CcPhInv>?</CcPhInv>
                    <VarianceKey>?</VarianceKey>
                    <SernoProf>?</SernoProf>
                    <Repmanprof>?</Repmanprof>
                    <NegStocks>?</NegStocks>
                    <QmRgmts>?</QmRgmts>
                    <PlngCycle>?</PlngCycle>
                    <RoundProf>?</RoundProf>
                    <Refmatcons>?</Refmatcons>
                    <DToRefM>?</DToRefM>
                    <MultRefM>?</MultRefM>
                    <AutoReset>?</AutoReset>
                    <ExCertId>?</ExCertId>
                    <ExCertNoNew>?</ExCertNoNew>
                    <ExCertDt>?</ExCertDt>
                    <MilitId>?</MilitId>
                    <InspInt>?</InspInt>
                    <CoProduct>?</CoProduct>
                    <PlanStrgp>?</PlanStrgp>
                    <SlocExprc>?</SlocExprc>
                    <BulkMat>?</BulkMat>
                    <CcFixed>?</CcFixed>
                    <DetermGrp>?</DetermGrp>
                    <QmAuthgrp>?</QmAuthgrp>
                    <TaskListType>?</TaskListType>
                    <PurStatus>?</PurStatus>
                    <Prodprof>?</Prodprof>
                    <SaftyTId>?</SaftyTId>
                    <Safetytime>?</Safetytime>
                    <PlordCtrl>?</PlordCtrl>
                    <Batchentry>?</Batchentry>
                    <Pvalidfrom>?</Pvalidfrom>
                    <Matfrgtgrp>?</Matfrgtgrp>
                    <Prodverscs>?</Prodverscs>
                    <MatCfop>?</MatCfop>
                    <EuListNo>?</EuListNo>
                    <EuMatGrp>?</EuMatGrp>
                    <CasNo>?</CasNo>
                    <ProdcomNo>?</ProdcomNo>
                    <CtrlCode>?</CtrlCode>
                    <JitRelvt>?</JitRelvt>
                    <MatGrpTrans>?</MatGrpTrans>
                    <HandlgGrp>?</HandlgGrp>
                    <SupplyArea>?</SupplyArea>
                    <FairShareRule>?</FairShareRule>
                    <PushDistrib>?</PushDistrib>
                    <DeployHoriz>?</DeployHoriz>
                    <MinLotSize>?</MinLotSize>
                    <MaxLotSize>?</MaxLotSize>
                    <FixLotSize>?</FixLotSize>
                    <LotIncrement>?</LotIncrement>
                    <ProdConvType>?</ProdConvType>
                    <DistrProf>?</DistrProf>
                    <PeriodProfileSafetyTime>?</PeriodProfileSafetyTime>
                    <FxdPrice>?</FxdPrice>
                    <AvailCheckAllProjSegments>?</AvailCheckAllProjSegments>
                    <Overallprf>?</Overallprf>
                    <MrpRelevancyDepRequirements>?</MrpRelevancyDepRequirements>
                    <MinSafetyStk>?</MinSafetyStk>
                    <NoCosting>?</NoCosting>
                    <UnitGroup>?</UnitGroup>
                    <FollowUpExternal>?</FollowUpExternal>
                    <FollowUpGuid>?</FollowUpGuid>
                    <FollowUpVersion>?</FollowUpVersion>
                    <RefmatconsExternal>?</RefmatconsExternal>
                    <RefmatconsGuid>?</RefmatconsGuid>
                    <RefmatconsVersion>?</RefmatconsVersion>
                    <SalesView>?</SalesView>
                    <PurchView>?</PurchView>
                    <MrpView>?</MrpView>
                    <ForecastView>?</ForecastView>
                    <WorkSchedView>?</WorkSchedView>
                    <PrtView>?</PrtView>
                    <StorageView>?</StorageView>
                    <WarehouseView>?</WarehouseView>
                    <QualityView>?</QualityView>
                    <AccountView>?</AccountView>
                    <CostView>?</CostView>
                    <RotationDate>?</RotationDate>
                    <OriginalBatchFlag>?</OriginalBatchFlag>
                    <OriginalBatchRefMaterial>?</OriginalBatchRefMaterial>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <OriginalBatchRefMaterialE>?</OriginalBatchRefMaterialE>
                    <OriginalBatchRefMaterialG>?</OriginalBatchRefMaterialG>
                    <OriginalBatchRefMaterialV>?</OriginalBatchRefMaterialV>
                    <IuidRelevant>?</IuidRelevant>
                    <IuidType>?</IuidType>
                    <UidIea>?</UidIea>
                    <SegmentationStrategy>?</SegmentationStrategy>
                    <SegmentationStatus>?</SegmentationStatus>
                    <ConsumptionPriority>?</ConsumptionPriority>
                    <DiscreteBatchFlag>?</DiscreteBatchFlag>
                    <StockProtectionInd>?</StockProtectionInd>
                    <DefaultStockSegment>?</DefaultStockSegment>
                    <AdvPlngInd>?</AdvPlngInd>
                    <MaterialLong>?</MaterialLong>
                    <FollowUpLong>?</FollowUpLong>
                    <RefmatconsLong>?</RefmatconsLong>
                    <OriginalBatchRefMaterialL>?</OriginalBatchRefMaterialL>
                    <DefSegLong>?</DefSegLong>
                    <Symbol>?</Symbol>
                </item>
            </Plantdata>
            <!--Optional:-->
            <Plantdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <DelFlag>?</DelFlag>
                    <AbcId>?</AbcId>
                    <CritPart>?</CritPart>
                    <PurGroup>?</PurGroup>
                    <IssueUnit>?</IssueUnit>
                    <IssueUnitIso>?</IssueUnitIso>
                    <Mrpprofile>?</Mrpprofile>
                    <MrpType>?</MrpType>
                    <MrpCtrler>?</MrpCtrler>
                    <PlndDelry>?</PlndDelry>
                    <GrPrTime>?</GrPrTime>
                    <PeriodInd>?</PeriodInd>
                    <AssyScrap>?</AssyScrap>
                    <Lotsizekey>?</Lotsizekey>
                    <ProcType>?</ProcType>
                    <Spproctype>?</Spproctype>
                    <ReorderPt>?</ReorderPt>
                    <SafetyStk>?</SafetyStk>
                    <Minlotsize>?</Minlotsize>
                    <Maxlotsize>?</Maxlotsize>
                    <FixedLot>?</FixedLot>
                    <RoundVal>?</RoundVal>
                    <MaxStock>?</MaxStock>
                    <OrdCosts>?</OrdCosts>
                    <DepReqId>?</DepReqId>
                    <StorCosts>?</StorCosts>
                    <AltBomId>?</AltBomId>
                    <Discontinu>?</Discontinu>
                    <EffODay>?</EffODay>
                    <FollowUp>?</FollowUp>
                    <GrpReqmts>?</GrpReqmts>
                    <MixedMrp>?</MixedMrp>
                    <SmKey>?</SmKey>
                    <Backflush>?</Backflush>
                    <ProductionScheduler>?</ProductionScheduler>
                    <ProcTime>?</ProcTime>
                    <Setuptime>?</Setuptime>
                    <Interop>?</Interop>
                    <BaseQty>?</BaseQty>
                    <Inhseprodt>?</Inhseprodt>
                    <Stgeperiod>?</Stgeperiod>
                    <StgePdUn>?</StgePdUn>
                    <StgePdUnIso>?</StgePdUnIso>
                    <OverTol>?</OverTol>
                    <Unlimited>?</Unlimited>
                    <UnderTol>?</UnderTol>
                    <Replentime>?</Replentime>
                    <ReplacePt>?</ReplacePt>
                    <IndPostToInspStock>?</IndPostToInspStock>
                    <CtrlKey>?</CtrlKey>
                    <DocReqd>?</DocReqd>
                    <Loadinggrp>?</Loadinggrp>
                    <BatchMgmt>?</BatchMgmt>
                    <Quotausage>?</Quotausage>
                    <ServLevel>?</ServLevel>
                    <SplitInd>?</SplitInd>
                    <Availcheck>?</Availcheck>
                    <FyVariant>?</FyVariant>
                    <CorrFact>?</CorrFact>
                    <SetupTime>?</SetupTime>
                    <BaseQtyPlan>?</BaseQtyPlan>
                    <ShipProcTime>?</ShipProcTime>
                    <SupSource>?</SupSource>
                    <AutoPOrd>?</AutoPOrd>
                    <Sourcelist>?</Sourcelist>
                    <CommCode>?</CommCode>
                    <Countryori>?</Countryori>
                    <CountryoriIso>?</CountryoriIso>
                    <Regionorig>?</Regionorig>
                    <CommCoUn>?</CommCoUn>
                    <CommCoUnIso>?</CommCoUnIso>
                    <Expimpgrp>?</Expimpgrp>
                    <ProfitCtr>?</ProfitCtr>
                    <PpcPlCal>?</PpcPlCal>
                    <RepManuf>?</RepManuf>
                    <PlTiFnce>?</PlTiFnce>
                    <Consummode>?</Consummode>
                    <BwdCons>?</BwdCons>
                    <FwdCons>?</FwdCons>
                    <AlternativeBom>?</AlternativeBom>
                    <BomUsage>?</BomUsage>
                    <Planlistgrp>?</Planlistgrp>
                    <Planlistcnt>?</Planlistcnt>
                    <LotSize>?</LotSize>
                    <Specprocty>?</Specprocty>
                    <ProdUnit>?</ProdUnit>
                    <ProdUnitIso>?</ProdUnitIso>
                    <IssStLoc>?</IssStLoc>
                    <MrpGroup>?</MrpGroup>
                    <CompScrap>?</CompScrap>
                    <CertType>?</CertType>
                    <CycleTime>?</CycleTime>
                    <Covprofile>?</Covprofile>
                    <CcPhInv>?</CcPhInv>
                    <VarianceKey>?</VarianceKey>
                    <SernoProf>?</SernoProf>
                    <Repmanprof>?</Repmanprof>
                    <NegStocks>?</NegStocks>
                    <QmRgmts>?</QmRgmts>
                    <PlngCycle>?</PlngCycle>
                    <RoundProf>?</RoundProf>
                    <Refmatcons>?</Refmatcons>
                    <DToRefM>?</DToRefM>
                    <MultRefM>?</MultRefM>
                    <AutoReset>?</AutoReset>
                    <ExCertId>?</ExCertId>
                    <ExCertNoNew>?</ExCertNoNew>
                    <ExCertDt>?</ExCertDt>
                    <MilitId>?</MilitId>
                    <InspInt>?</InspInt>
                    <CoProduct>?</CoProduct>
                    <PlanStrgp>?</PlanStrgp>
                    <SlocExprc>?</SlocExprc>
                    <BulkMat>?</BulkMat>
                    <CcFixed>?</CcFixed>
                    <DetermGrp>?</DetermGrp>
                    <QmAuthgrp>?</QmAuthgrp>
                    <TaskListType>?</TaskListType>
                    <PurStatus>?</PurStatus>
                    <Prodprof>?</Prodprof>
                    <SaftyTId>?</SaftyTId>
                    <Safetytime>?</Safetytime>
                    <PlordCtrl>?</PlordCtrl>
                    <Batchentry>?</Batchentry>
                    <Pvalidfrom>?</Pvalidfrom>
                    <Matfrgtgrp>?</Matfrgtgrp>
                    <Prodverscs>?</Prodverscs>
                    <MatCfop>?</MatCfop>
                    <EuListNo>?</EuListNo>
                    <EuMatGrp>?</EuMatGrp>
                    <CasNo>?</CasNo>
                    <ProdcomNo>?</ProdcomNo>
                    <CtrlCode>?</CtrlCode>
                    <JitRelvt>?</JitRelvt>
                    <MatGrpTrans>?</MatGrpTrans>
                    <HandlgGrp>?</HandlgGrp>
                    <SupplyArea>?</SupplyArea>
                    <FairShareRule>?</FairShareRule>
                    <PushDistrib>?</PushDistrib>
                    <DeployHoriz>?</DeployHoriz>
                    <MinLotSize>?</MinLotSize>
                    <MaxLotSize>?</MaxLotSize>
                    <FixLotSize>?</FixLotSize>
                    <LotIncrement>?</LotIncrement>
                    <ProdConvType>?</ProdConvType>
                    <DistrProf>?</DistrProf>
                    <PeriodProfileSafetyTime>?</PeriodProfileSafetyTime>
                    <FxdPrice>?</FxdPrice>
                    <AvailCheckAllProjSegments>?</AvailCheckAllProjSegments>
                    <Overallprf>?</Overallprf>
                    <MrpRelevancyDepRequirements>?</MrpRelevancyDepRequirements>
                    <MinSafetyStk>?</MinSafetyStk>
                    <NoCosting>?</NoCosting>
                    <UnitGroup>?</UnitGroup>
                    <FollowUpExternal>?</FollowUpExternal>
                    <FollowUpGuid>?</FollowUpGuid>
                    <FollowUpVersion>?</FollowUpVersion>
                    <RefmatconsExternal>?</RefmatconsExternal>
                    <RefmatconsGuid>?</RefmatconsGuid>
                    <RefmatconsVersion>?</RefmatconsVersion>
                    <RotationDate>?</RotationDate>
                    <OriginalBatchFlag>?</OriginalBatchFlag>
                    <OriginalBatchRefMaterial>?</OriginalBatchRefMaterial>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <OriginalBatchRefMaterialE>?</OriginalBatchRefMaterialE>
                    <OriginalBatchRefMaterialV>?</OriginalBatchRefMaterialV>
                    <OriginalBatchRefMaterialG>?</OriginalBatchRefMaterialG>
                    <IuidRelevant>?</IuidRelevant>
                    <IuidType>?</IuidType>
                    <UidIea>?</UidIea>
                    <SegmentationStrategy>?</SegmentationStrategy>
                    <SegmentationStatus>?</SegmentationStatus>
                    <ConsumptionPriority>?</ConsumptionPriority>
                    <DiscreteBatchFlag>?</DiscreteBatchFlag>
                    <StockProtectionInd>?</StockProtectionInd>
                    <DefaultStockSegment>?</DefaultStockSegment>
                    <AdvPlngInd>?</AdvPlngInd>
                    <MaterialLong>?</MaterialLong>
                    <FollowUpLong>?</FollowUpLong>
                    <RefmatconsLong>?</RefmatconsLong>
                    <OriginalBatchRefMaterialL>?</OriginalBatchRefMaterialL>
                    <DefSegLong>?</DefSegLong>
                    <Symbol>?</Symbol>
                </item>
            </Plantdatax>
            <!--Optional:-->
            <Prtdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <CreateLoadRecs>?</CreateLoadRecs>
                    <CtrlKey>?</CtrlKey>
                    <CtrlKeyNoChg>?</CtrlKeyNoChg>
                    <GrpKey1>?</GrpKey1>
                    <GrpKey2>?</GrpKey2>
                    <PrtUsage>?</PrtUsage>
                    <StdTextKey>?</StdTextKey>
                    <RefKeyNoChg>?</RefKeyNoChg>
                    <StartRefDate>?</StartRefDate>
                    <StRefDateNoChg>?</StRefDateNoChg>
                    <StartOffset>?</StartOffset>
                    <StartOffsetUnit>?</StartOffsetUnit>
                    <StartOffsetUnitIso>?</StartOffsetUnitIso>
                    <StartOffsetNoChg>?</StartOffsetNoChg>
                    <EndRefDate>?</EndRefDate>
                    <EndRefDateNoChg>?</EndRefDateNoChg>
                    <EndOffset>?</EndOffset>
                    <EndOffsetUnit>?</EndOffsetUnit>
                    <EndOffsetUnitIso>?</EndOffsetUnitIso>
                    <EndOffsetNoChg>?</EndOffsetNoChg>
                    <FormulaTotQty>?</FormulaTotQty>
                    <FormulaTotQtyNoChg>?</FormulaTotQtyNoChg>
                    <FormulaTotUsage>?</FormulaTotUsage>
                    <FormulaTotUsageNoChg>?</FormulaTotUsageNoChg>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Prtdata>
            <!--Optional:-->
            <Prtdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <CreateLoadRecs>?</CreateLoadRecs>
                    <CtrlKey>?</CtrlKey>
                    <CtrlKeyNoChg>?</CtrlKeyNoChg>
                    <GrpKey1>?</GrpKey1>
                    <GrpKey2>?</GrpKey2>
                    <PrtUsage>?</PrtUsage>
                    <StdTextKey>?</StdTextKey>
                    <RefKeyNoChg>?</RefKeyNoChg>
                    <StartRefDate>?</StartRefDate>
                    <StRefDateNoChg>?</StRefDateNoChg>
                    <StartOffset>?</StartOffset>
                    <StartOffsetUnit>?</StartOffsetUnit>
                    <StartOffsetUnitIso>?</StartOffsetUnitIso>
                    <StartOffsetNoChg>?</StartOffsetNoChg>
                    <EndRefDate>?</EndRefDate>
                    <EndRefDateNoChg>?</EndRefDateNoChg>
                    <EndOffset>?</EndOffset>
                    <EndOffsetUnit>?</EndOffsetUnit>
                    <EndOffsetUnitIso>?</EndOffsetUnitIso>
                    <EndOffsetNoChg>?</EndOffsetNoChg>
                    <FormulaTotQty>?</FormulaTotQty>
                    <FormulaTotQtyNoChg>?</FormulaTotQtyNoChg>
                    <FormulaTotUsage>?</FormulaTotUsage>
                    <FormulaTotUsageNoChg>?</FormulaTotUsageNoChg>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Prtdatax>
            <!--Optional:-->
            <Returnmessages>
                <!--Zero or more repetitions:-->
                <item>
                    <Type>?</Type>
                    <Id>?</Id>
                    <Number>?</Number>
                    <Message>?</Message>
                    <LogNo>?</LogNo>
                    <LogMsgNo>?</LogMsgNo>
                    <MessageV1>?</MessageV1>
                    <MessageV2>?</MessageV2>
                    <MessageV3>?</MessageV3>
                    <MessageV4>?</MessageV4>
                    <Parameter>?</Parameter>
                    <Row>?</Row>
                    <Field>?</Field>
                    <System>?</System>
                </item>
            </Returnmessages>
            <!--Optional:-->
            <Salesdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <SalesOrg>?</SalesOrg>
                    <DistrChan>?</DistrChan>
                    <DelFlag>?</DelFlag>
                    <MatlStats>?</MatlStats>
                    <RebateGrp>?</RebateGrp>
                    <CommGroup>?</CommGroup>
                    <CashDisc>?</CashDisc>
                    <SalStatus>?</SalStatus>
                    <ValidFrom>?</ValidFrom>
                    <MinOrder>?</MinOrder>
                    <MinDely>?</MinDely>
                    <MinMto>?</MinMto>
                    <DelyUnit>?</DelyUnit>
                    <DelyUom>?</DelyUom>
                    <DelyUomIso>?</DelyUomIso>
                    <SalesUnit>?</SalesUnit>
                    <SalesUnitIso>?</SalesUnitIso>
                    <ItemCat>?</ItemCat>
                    <DelygPlnt>?</DelygPlnt>
                    <ProdHier>?</ProdHier>
                    <PrRefMat>?</PrRefMat>
                    <MatPrGrp>?</MatPrGrp>
                    <AcctAssgt>?</AcctAssgt>
                    <MatlGrp1>?</MatlGrp1>
                    <MatlGrp2>?</MatlGrp2>
                    <MatlGrp3>?</MatlGrp3>
                    <MatlGrp4>?</MatlGrp4>
                    <MatlGrp5>?</MatlGrp5>
                    <ProdAtt1>?</ProdAtt1>
                    <ProdAtt2>?</ProdAtt2>
                    <ProdAtt3>?</ProdAtt3>
                    <ProdAtt4>?</ProdAtt4>
                    <ProdAtt5>?</ProdAtt5>
                    <ProdAtt6>?</ProdAtt6>
                    <ProdAtt7>?</ProdAtt7>
                    <ProdAtt8>?</ProdAtt8>
                    <ProdAtt9>?</ProdAtt9>
                    <ProdAtt10>?</ProdAtt10>
                    <RoundProf>?</RoundProf>
                    <VarSalesUn>?</VarSalesUn>
                    <UnitGroup>?</UnitGroup>
                    <PrRefMatExternal>?</PrRefMatExternal>
                    <PrRefMatGuid>?</PrRefMatGuid>
                    <PrRefMatVersion>?</PrRefMatVersion>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                    <PrRefMatLong>?</PrRefMatLong>
                </item>
            </Salesdata>
            <!--Optional:-->
            <Salesdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <SalesOrg>?</SalesOrg>
                    <DistrChan>?</DistrChan>
                    <DelFlag>?</DelFlag>
                    <MatlStats>?</MatlStats>
                    <RebateGrp>?</RebateGrp>
                    <CommGroup>?</CommGroup>
                    <CashDisc>?</CashDisc>
                    <SalStatus>?</SalStatus>
                    <ValidFrom>?</ValidFrom>
                    <MinOrder>?</MinOrder>
                    <MinDely>?</MinDely>
                    <MinMto>?</MinMto>
                    <DelyUnit>?</DelyUnit>
                    <DelyUom>?</DelyUom>
                    <DelyUomIso>?</DelyUomIso>
                    <SalesUnit>?</SalesUnit>
                    <SalesUnitIso>?</SalesUnitIso>
                    <ItemCat>?</ItemCat>
                    <DelygPlnt>?</DelygPlnt>
                    <ProdHier>?</ProdHier>
                    <PrRefMat>?</PrRefMat>
                    <MatPrGrp>?</MatPrGrp>
                    <AcctAssgt>?</AcctAssgt>
                    <MatlGrp1>?</MatlGrp1>
                    <MatlGrp2>?</MatlGrp2>
                    <MatlGrp3>?</MatlGrp3>
                    <MatlGrp4>?</MatlGrp4>
                    <MatlGrp5>?</MatlGrp5>
                    <ProdAtt1>?</ProdAtt1>
                    <ProdAtt2>?</ProdAtt2>
                    <ProdAtt3>?</ProdAtt3>
                    <ProdAtt4>?</ProdAtt4>
                    <ProdAtt5>?</ProdAtt5>
                    <ProdAtt6>?</ProdAtt6>
                    <ProdAtt7>?</ProdAtt7>
                    <ProdAtt8>?</ProdAtt8>
                    <ProdAtt9>?</ProdAtt9>
                    <ProdAtt10>?</ProdAtt10>
                    <RoundProf>?</RoundProf>
                    <VarSalesUn>?</VarSalesUn>
                    <UnitGroup>?</UnitGroup>
                    <PrRefMatExternal>?</PrRefMatExternal>
                    <PrRefMatGuid>?</PrRefMatGuid>
                    <PrRefMatVersion>?</PrRefMatVersion>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                    <PrRefMatLong>?</PrRefMatLong>
                </item>
            </Salesdatax>
            <!--Optional:-->
            <Storagelocationdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <StgeLoc>?</StgeLoc>
                    <DelFlag>?</DelFlag>
                    <MrpInd>?</MrpInd>
                    <SpecProc>?</SpecProc>
                    <ReorderPt>?</ReorderPt>
                    <ReplQty>?</ReplQty>
                    <StgeBin>?</StgeBin>
                    <PickgArea>?</PickgArea>
                    <InvCorrFac>?</InvCorrFac>
                    <MrpView>?</MrpView>
                    <StorageView>?</StorageView>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Storagelocationdata>
            <!--Optional:-->
            <Storagelocationdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <StgeLoc>?</StgeLoc>
                    <DelFlag>?</DelFlag>
                    <MrpInd>?</MrpInd>
                    <SpecProc>?</SpecProc>
                    <ReorderPt>?</ReorderPt>
                    <ReplQty>?</ReplQty>
                    <StgeBin>?</StgeBin>
                    <PickgArea>?</PickgArea>
                    <InvCorrFac>?</InvCorrFac>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Storagelocationdatax>
            <!--Optional:-->
            <Storagetypedata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <WhseNo>?</WhseNo>
                    <StgeType>?</StgeType>
                    <DelFlag>?</DelFlag>
                    <StgeBin>?</StgeBin>
                    <MaxSbQty>?</MaxSbQty>
                    <MinSbQty>?</MinSbQty>
                    <CtrlQty>?</CtrlQty>
                    <ReplenQty>?</ReplenQty>
                    <PickArea>?</PickArea>
                    <RoundQty>?</RoundQty>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Storagetypedata>
            <!--Optional:-->
            <Storagetypedatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <WhseNo>?</WhseNo>
                    <StgeType>?</StgeType>
                    <DelFlag>?</DelFlag>
                    <StgeBin>?</StgeBin>
                    <MaxSbQty>?</MaxSbQty>
                    <MinSbQty>?</MinSbQty>
                    <CtrlQty>?</CtrlQty>
                    <ReplenQty>?</ReplenQty>
                    <PickArea>?</PickArea>
                    <RoundQty>?</RoundQty>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Storagetypedatax>
            <!--Optional:-->
            <Taxclassifications>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Depcountry>?</Depcountry>
                    <DepcountryIso>?</DepcountryIso>
                    <TaxType1>?</TaxType1>
                    <Taxclass1>?</Taxclass1>
                    <TaxType2>?</TaxType2>
                    <Taxclass2>?</Taxclass2>
                    <TaxType3>?</TaxType3>
                    <Taxclass3>?</Taxclass3>
                    <TaxType4>?</TaxType4>
                    <Taxclass4>?</Taxclass4>
                    <TaxType5>?</TaxType5>
                    <Taxclass5>?</Taxclass5>
                    <TaxType6>?</TaxType6>
                    <Taxclass6>?</Taxclass6>
                    <TaxType7>?</TaxType7>
                    <Taxclass7>?</Taxclass7>
                    <TaxType8>?</TaxType8>
                    <Taxclass8>?</Taxclass8>
                    <TaxType9>?</TaxType9>
                    <Taxclass9>?</Taxclass9>
                    <TaxInd>?</TaxInd>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Taxclassifications>
            <!--Optional:-->
            <Totalconsumption>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <FirstDay>?</FirstDay>
                    <ConsValue>?</ConsValue>
                    <CorrValue>?</CorrValue>
                    <ValRatio>?</ValRatio>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Totalconsumption>
            <!--Optional:-->
            <Unitsofmeasure>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <AltUnit>?</AltUnit>
                    <AltUnitIso>?</AltUnitIso>
                    <Numerator>?</Numerator>
                    <Denominatr>?</Denominatr>
                    <EanUpc>?</EanUpc>
                    <EanCat>?</EanCat>
                    <Length>?</Length>
                    <Width>?</Width>
                    <Height>?</Height>
                    <UnitDim>?</UnitDim>
                    <UnitDimIso>?</UnitDimIso>
                    <Volume>?</Volume>
                    <Volumeunit>?</Volumeunit>
                    <VolumeunitIso>?</VolumeunitIso>
                    <GrossWt>?</GrossWt>
                    <UnitOfWt>?</UnitOfWt>
                    <UnitOfWtIso>?</UnitOfWtIso>
                    <DelFlag>?</DelFlag>
                    <SubUom>?</SubUom>
                    <SubUomIso>?</SubUomIso>
                    <GtinVariant>?</GtinVariant>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <NestingFactor>?</NestingFactor>
                    <MaximumStacking>?</MaximumStacking>
                    <CapacityUsage>?</CapacityUsage>
                    <EwmCwUomType>?</EwmCwUomType>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Unitsofmeasure>
            <!--Optional:-->
            <Unitsofmeasurex>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <AltUnit>?</AltUnit>
                    <AltUnitIso>?</AltUnitIso>
                    <Numerator>?</Numerator>
                    <Denominatr>?</Denominatr>
                    <EanUpc>?</EanUpc>
                    <EanCat>?</EanCat>
                    <Length>?</Length>
                    <Width>?</Width>
                    <Height>?</Height>
                    <UnitDim>?</UnitDim>
                    <UnitDimIso>?</UnitDimIso>
                    <Volume>?</Volume>
                    <Volumeunit>?</Volumeunit>
                    <VolumeunitIso>?</VolumeunitIso>
                    <GrossWt>?</GrossWt>
                    <UnitOfWt>?</UnitOfWt>
                    <UnitOfWtIso>?</UnitOfWtIso>
                    <SubUom>?</SubUom>
                    <SubUomIso>?</SubUomIso>
                    <GtinVariant>?</GtinVariant>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <NestingFactor>?</NestingFactor>
                    <MaximumStacking>?</MaximumStacking>
                    <CapacityUsage>?</CapacityUsage>
                    <EwmCwUomType>?</EwmCwUomType>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Unitsofmeasurex>
            <!--Optional:-->
            <Unplndconsumption>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <Plant>?</Plant>
                    <FirstDay>?</FirstDay>
                    <ConsValue>?</ConsValue>
                    <CorrValue>?</CorrValue>
                    <ValRatio>?</ValRatio>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Unplndconsumption>
            <!--Optional:-->
            <Valuationdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <ValArea>?</ValArea>
                    <ValType>?</ValType>
                    <DelFlag>?</DelFlag>
                    <PriceCtrl>?</PriceCtrl>
                    <MovingPr>?</MovingPr>
                    <StdPrice>?</StdPrice>
                    <PriceUnit>?</PriceUnit>
                    <ValClass>?</ValClass>
                    <PrCtrlPp>?</PrCtrlPp>
                    <MovPrPp>?</MovPrPp>
                    <StdPrPp>?</StdPrPp>
                    <PrUnitPp>?</PrUnitPp>
                    <VclassPp>?</VclassPp>
                    <PrCtrlPy>?</PrCtrlPy>
                    <MovPrPy>?</MovPrPy>
                    <StdPrPy>?</StdPrPy>
                    <VclassPy>?</VclassPy>
                    <PrUnitPy>?</PrUnitPy>
                    <ValCat>?</ValCat>
                    <FuturePr>?</FuturePr>
                    <ValidFrom>?</ValidFrom>
                    <Taxprice1>?</Taxprice1>
                    <Commprice1>?</Commprice1>
                    <Taxprice3>?</Taxprice3>
                    <Commprice3>?</Commprice3>
                    <PlndPrice>?</PlndPrice>
                    <Plndprice1>?</Plndprice1>
                    <Plndprice2>?</Plndprice2>
                    <Plndprice3>?</Plndprice3>
                    <Plndprdate1>?</Plndprdate1>
                    <Plndprdate2>?</Plndprdate2>
                    <Plndprdate3>?</Plndprdate3>
                    <LifoFifo>?</LifoFifo>
                    <Poolnumber>?</Poolnumber>
                    <Taxprice2>?</Taxprice2>
                    <Commprice2>?</Commprice2>
                    <DevalInd>?</DevalInd>
                    <OrigGroup>?</OrigGroup>
                    <OverheadGrp>?</OverheadGrp>
                    <QtyStruct>?</QtyStruct>
                    <MlActive>?</MlActive>
                    <MlSettle>?</MlSettle>
                    <OrigMat>?</OrigMat>
                    <VmSoStk>?</VmSoStk>
                    <VmPStock>?</VmPStock>
                    <MatlUsage>?</MatlUsage>
                    <MatOrigin>?</MatOrigin>
                    <InHouse>?</InHouse>
                    <TaxCmlUn>?</TaxCmlUn>
                    <AccountView>?</AccountView>
                    <CostView>?</CostView>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Valuationdata>
            <!--Optional:-->
            <Valuationdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <ValArea>?</ValArea>
                    <ValType>?</ValType>
                    <DelFlag>?</DelFlag>
                    <PriceCtrl>?</PriceCtrl>
                    <MovingPr>?</MovingPr>
                    <StdPrice>?</StdPrice>
                    <PriceUnit>?</PriceUnit>
                    <ValClass>?</ValClass>
                    <PrCtrlPp>?</PrCtrlPp>
                    <MovPrPp>?</MovPrPp>
                    <StdPrPp>?</StdPrPp>
                    <PrUnitPp>?</PrUnitPp>
                    <VclassPp>?</VclassPp>
                    <PrCtrlPy>?</PrCtrlPy>
                    <MovPrPy>?</MovPrPy>
                    <StdPrPy>?</StdPrPy>
                    <VclassPy>?</VclassPy>
                    <PrUnitPy>?</PrUnitPy>
                    <ValCat>?</ValCat>
                    <FuturePr>?</FuturePr>
                    <ValidFrom>?</ValidFrom>
                    <Taxprice1>?</Taxprice1>
                    <Commprice1>?</Commprice1>
                    <Taxprice3>?</Taxprice3>
                    <Commprice3>?</Commprice3>
                    <PlndPrice>?</PlndPrice>
                    <Plndprice1>?</Plndprice1>
                    <Plndprice2>?</Plndprice2>
                    <Plndprice3>?</Plndprice3>
                    <Plndprdate1>?</Plndprdate1>
                    <Plndprdate2>?</Plndprdate2>
                    <Plndprdate3>?</Plndprdate3>
                    <LifoFifo>?</LifoFifo>
                    <Poolnumber>?</Poolnumber>
                    <Taxprice2>?</Taxprice2>
                    <Commprice2>?</Commprice2>
                    <DevalInd>?</DevalInd>
                    <OrigGroup>?</OrigGroup>
                    <OverheadGrp>?</OverheadGrp>
                    <QtyStruct>?</QtyStruct>
                    <MlActive>?</MlActive>
                    <MlSettle>?</MlSettle>
                    <OrigMat>?</OrigMat>
                    <VmSoStk>?</VmSoStk>
                    <VmPStock>?</VmPStock>
                    <MatlUsage>?</MatlUsage>
                    <MatOrigin>?</MatOrigin>
                    <InHouse>?</InHouse>
                    <TaxCmlUn>?</TaxCmlUn>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Valuationdatax>
            <!--Optional:-->
            <Warehousenumberdata>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <WhseNo>?</WhseNo>
                    <DelFlag>?</DelFlag>
                    <Stgesector>?</Stgesector>
                    <Placement>?</Placement>
                    <Withdrawal>?</Withdrawal>
                    <LEquip1>?</LEquip1>
                    <LEquip2>?</LEquip2>
                    <LEquip3>?</LEquip3>
                    <LeqUnit1>?</LeqUnit1>
                    <LeqUnit1Iso>?</LeqUnit1Iso>
                    <LeqUnit2>?</LeqUnit2>
                    <LeqUnit2Iso>?</LeqUnit2Iso>
                    <LeqUnit3>?</LeqUnit3>
                    <LeqUnit3Iso>?</LeqUnit3Iso>
                    <Unittype1>?</Unittype1>
                    <Unittype2>?</Unittype2>
                    <Unittype3>?</Unittype3>
                    <WmUnit>?</WmUnit>
                    <WmUnitIso>?</WmUnitIso>
                    <AddToStk>?</AddToStk>
                    <BlockStge>?</BlockStge>
                    <MsgToIm>?</MsgToIm>
                    <SpecMvmt>?</SpecMvmt>
                    <CapyUsage>?</CapyUsage>
                    <ProcureUn>?</ProcureUn>
                    <ProcureUnIso>?</ProcureUnIso>
                    <StgeType>?</StgeType>
                    <RefUnit>?</RefUnit>
                    <_--32stepPick>?</_--32stepPick>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Warehousenumberdata>
            <!--Optional:-->
            <Warehousenumberdatax>
                <!--Zero or more repetitions:-->
                <item>
                    <Function>?</Function>
                    <Material>?</Material>
                    <WhseNo>?</WhseNo>
                    <DelFlag>?</DelFlag>
                    <Stgesector>?</Stgesector>
                    <Placement>?</Placement>
                    <Withdrawal>?</Withdrawal>
                    <LEquip1>?</LEquip1>
                    <LEquip2>?</LEquip2>
                    <LEquip3>?</LEquip3>
                    <LeqUnit1>?</LeqUnit1>
                    <LeqUnit1Iso>?</LeqUnit1Iso>
                    <LeqUnit2>?</LeqUnit2>
                    <LeqUnit2Iso>?</LeqUnit2Iso>
                    <LeqUnit3>?</LeqUnit3>
                    <LeqUnit3Iso>?</LeqUnit3Iso>
                    <Unittype1>?</Unittype1>
                    <Unittype2>?</Unittype2>
                    <Unittype3>?</Unittype3>
                    <WmUnit>?</WmUnit>
                    <WmUnitIso>?</WmUnitIso>
                    <AddToStk>?</AddToStk>
                    <BlockStge>?</BlockStge>
                    <MsgToIm>?</MsgToIm>
                    <SpecMvmt>?</SpecMvmt>
                    <CapyUsage>?</CapyUsage>
                    <ProcureUn>?</ProcureUn>
                    <ProcureUnIso>?</ProcureUnIso>
                    <StgeType>?</StgeType>
                    <RefUnit>?</RefUnit>
                    <_--32stepPick>?</_--32stepPick>
                    <MaterialExternal>?</MaterialExternal>
                    <MaterialGuid>?</MaterialGuid>
                    <MaterialVersion>?</MaterialVersion>
                    <MaterialLong>?</MaterialLong>
                </item>
            </Warehousenumberdatax>
            <!--Optional:-->
            <ZmdmHh>
                <MdmVbeln>?</MdmVbeln>
                <Function>?</Function>
            </ZmdmHh>
            <!--Optional:-->
            <ZtmmMaraSpec>
                <!--Zero or more repetitions:-->
                <item>
                    <Mandt>?</Mandt>
                    <Matnr>?</Matnr>
                    <Zspec>?</Zspec>
                    <Zdraw>?</Zdraw>
                    <Zcatmngr>?</Zcatmngr>
                    <Zpurcatg>?</Zpurcatg>
                    <Zpurcat>?</Zpurcat>
                    <Zpurcatp>?</Zpurcatp>
                    <Zpartcat>?</Zpartcat>
                    <Zmatsubcat>?</Zmatsubcat>
                    <Zmatgroup>?</Zmatgroup>
                    <Zplatform>?</Zplatform>
                    <LcBname>?</LcBname>
                    <LcTs>?</LcTs>
                </item>
            </ZtmmMaraSpec>
        </urn:ZmdmMaterialSavedata>
    </soapenv:Body>
</soapenv:Envelope>